8074: To optimize Check-in multiple SharePoint documents in Power Automate
Plumsail/actions-docs pull request #13
Opened 2023-01-17 07:19 UTC by MaxAnshin

2023-01-18 07:43 UTC, cherinaa requested changes
@MaxAnshin Please, check my comments. 

The main message is "When you improve something, fix the mistakes if there are any. This also improves the article."

2023-01-18 07:43 UTC, cherinaa commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +As you may know, the **Check Out** and **Check In** functions in SharePoint are necessary to avoid confusion when several people edit the same file or document simultaneously. For example, during the
> where we multiple Check In SharePoint documents/files at once

It seems that words are swapped. "Multiple" refers to SharePoint documents/files, so it should be:

where we Check In **multiple SharePoint documents/files** at once

2023-01-18 07:43 UTC, cherinaa commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +~~~~~~~~~~~~~~
Let's make all titles on the same level. I didn't get the point of why "Case example" and "Related articles" are on the higher one.

2023-01-18 07:43 UTC, cherinaa commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +For this case, I will use *‘Get files (properties only)‘* from SharePoint Connector for getting properties of documents that need to be Checked In. I will also use `Check In SharePoint Document <../.
> For this case, I will use ‘Get files (properties only)‘ from SharePoint Connector for getting properties of documents that need to be Checked In. I will also use [Check In SharePoint Document](https://github.com/Plumsail/actions-docs/actions/sharepoint-processing.html#check-in-sharepoint-document) from Plumsail SP connector, which is a part of [Plumsail Actions](https://plumsail.com/actions) for each document that will be found on the first step.

Please, correct mistakes and inaccuracies as well when you adjust articles. In this paragraph:
For this case, I will use ‘Get files (properties only)‘ from SharePoint Connector **to get** properties of documents that need to be Checked In. I will also use [Check In SharePoint Document](https://github.com/Plumsail/actions-docs/actions/sharepoint-processing.html#check-in-sharepoint-document) from **the** Plumsail SP connector, which is a part of [Plumsail Actions](https://plumsail.com/actions), for each document **from** the first step.

2023-01-18 07:43 UTC, cherinaa commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
>  Manually trigger a flow
> For this case, I'm using the trigger to manual start of the flow. 
Here is a mess of words, it's better to correct. 
"manually start the flow" or "start the flow manually" would be better

2023-01-18 07:43 UTC, cherinaa commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +The action is using `OData filter <http://www.odata.org/documentation/odata-version-3-0/url-conventions/>`_ as a value of *‘Filter Query‘* field. I compare "CheckOutUser" field from document's proper
> If the value of this field is not equal null then that is mean this file has Check Out status.
Grammatical mistakes here:
equal **to** null
that **means** (instead of "that is mean")

2023-01-18 07:43 UTC, cherinaa commented on source/flow/how-tos/sharepoint/copy-document-set-to-another-library.rst
> +Related articles
Why different levels of headings? I think they should be at the same level 🤔
![image](https://user-images.githubusercontent.com/51232863/213110677-dcbb4727-0142-4bcc-b830-dbf011136693.png)

Check the rest and correct them. In some articles, you use different levels, and in others, the same. You need to pay attention to the type of underline.

2023-01-30 11:53 UTC, MaxAnshin commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +As you may know, the **Check Out** and **Check In** functions in SharePoint are necessary to avoid confusion when several people edit the same file or document simultaneously. For example, during the
Corrected

2023-01-30 11:53 UTC, MaxAnshin commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +~~~~~~~~~~~~~~
Corrected

2023-01-30 11:53 UTC, MaxAnshin commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +For this case, I will use *‘Get files (properties only)‘* from SharePoint Connector for getting properties of documents that need to be Checked In. I will also use `Check In SharePoint Document <../.
Corrected

2023-01-30 11:53 UTC, MaxAnshin commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
>  Manually trigger a flow
Corrected

2023-01-30 11:53 UTC, MaxAnshin commented on source/flow/how-tos/sharepoint/how-to-check-in-multiple-documents.rst
> +The action is using `OData filter <http://www.odata.org/documentation/odata-version-3-0/url-conventions/>`_ as a value of *‘Filter Query‘* field. I compare "CheckOutUser" field from document's proper
Corrected

2023-01-30 11:53 UTC, MaxAnshin commented on source/flow/how-tos/sharepoint/copy-document-set-to-another-library.rst
> +Related articles
Corrected

2023-01-31 15:08 UTC, merged